apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  NODE_ENV: production
  PORT: "3005"

  KAFKAJS_NO_PARTITIONER_WARNING: "1"

  GOOGLE_APPLICATION_CREDENTIALS: "./firebase-adminsdk.json"
